const now = new Date();
console.log("now:", now);
console.log("getFullYear:", now.getFullYear());
console.log("getMonth:", now.getMonth());
console.log("getDate:", now.getDate());
console.log("getDay:", now.getDay());
console.log("getHours:", now.getHours());
console.log("getMinutes:", now.getMinutes());
console.log("getSeconds:", now.getSeconds());
console.log("toDateString:", now.toDateString());
console.log("toTimeString():", now.toTimeString());
console.log("toISOString():", now.toISOString());
console.log("toLocaleDateString():", now.toLocaleDateString());
console.log("toISOString(vi-VI):", now.toLocaleDateString("vi-VI"));
// now.setHours(22, 10, 10, 10000);
console.log("now:", now.getTime());
const endDate = "2023-06-20T14:24:23.633Z";
const total = new Date(endDate) - now;
console.log("total:", total);
// const seconds = Math.floor(total / 1000) % 60;
// console.log("seconds:", seconds);
// const minutes = Math.floor(total / 1000 / 60) % 60;
// console.log("minutes:", minutes);
// const hours = Math.floor(total / 1000 / 60 / 60) % 24;
// console.log("hours:", hours);
const days = 24 * 60 * 60 * 1000;
const hours = 1 * 60 * 60 * 1000;
const minutes = 1 * 60 * 1000;
const seconds = 1 * 1000;
function countdown(endDate) {
  const day = document.querySelector(".day > .number");
  const hour = document.querySelector(".hour > .number");
  const minute = document.querySelector(".minute > .number");
  const second = document.querySelector(".second > .number");
  const timer = setInterval(function () {
    const now = new Date();
    let remainingTime = new Date(endDate) - now;
    const daysCount = Math.floor(remainingTime / days);
    remainingTime = remainingTime % days;
    const hoursCount = Math.floor(remainingTime / hours);
    remainingTime = remainingTime % hours;
    const minutesCount = Math.floor(remainingTime / minutes);
    remainingTime = remainingTime % minutes;
    const secondsCount = Math.floor(remainingTime / seconds);
    day.textContent = daysCount;
    hour.textContent = hoursCount;
    minute.textContent = minutesCount;
    second.textContent = secondsCount;
  }, 1000);
}
countdown("2023-06-20T14:24:23.633Z");
